### ISSUE TITLE
List of blog posts has numbered entries in reverse order

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#120]
The numbering in the [list of blog posts](https://wpewebkit.org/blog/) feels a bit odd:

![Screenshot of the blog post list](https://user-images.githubusercontent.com/723451/182156332-34e6c2be-eb53-41d0-bf2b-b52e97ca24fa.png)

- The numbers go up.
- The dates go down.

This is because the template is using an ordered list for the elements. We should use `list-style: none` or hide the numbering in some other way&mdash;it's fine to show the dates only without the number.

**Comment by meyerweb** [comment]
Addressed by https://github.com/Igalia/wpewebkit.org/pull/121; closing.
