### ISSUE TITLE
Mastodon Updates

### ISSUE THREAD

**Issue by bkardell** [Igalia/wpewebkit.org#130]
- [x]  create a mastodon account
- [x]  add links in the footer
- [x]  add a `rel="me"` 
- [x]  tweet the account info/update in the profile

**Comment by aperezdc** [comment]
Both footer link and `rel="me"` added in #140

**Comment by aperezdc** [comment]
Added the fediverse handle (`@WPEWebKit@floss.social`) to the Twitter profile as well:

![Screen capture of the @WPEWebKit Twitter profile](https://user-images.githubusercontent.com/723451/212904699-256ab97c-f59c-4e37-93d6-e7302a943085.png)

**Comment by aperezdc** [comment]
Closing, if there's anything I may have missed, please re-open the issue and comment (or file a new one) ✔️
