### ISSUE TITLE
No horizontal spacing between date and download button in release pages

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#150]
In any release page ([like this one](https://wpewebkit.org/release/wpewebkit-2.38.5.html)), there is no spacing at all between the “Download” button and the date:

![Screenshot of the affected web page area](https://user-images.githubusercontent.com/723451/219062262-e5daa29c-faf3-4d2e-8458-99901b4b6fcb.png)

The “Download” button probably should have less vertical padding, too.

**Comment by bkardell** [comment]
I'm so sorry I missed this!  It looks like this has been addressed, should we close this issue?
