### ISSUE TITLE
The broken line on the header doesn't point to "Get started" when visiting the "Get started" section

### ISSUE THREAD

**Issue by csaavedra** [Igalia/wpewebkit.org#188]
This is confusing. When opening "Get started", the arrow points to "Learn and discover" instead of the "Get started" button.

![image](https://github.com/Igalia/wpewebkit.org/assets/2523171/1dcfae71-5839-479f-8134-e1356c5c7a35)

I would expect something like this (with proper styling for the button, of course):

![image](https://github.com/Igalia/wpewebkit.org/assets/2523171/dac6c4cc-d64a-41e2-bc95-797a71d47bd9)

**Comment by bkardell** [comment]
@meyerweb

**Comment by meyerweb** [comment]
This is a hangover from the redesign, where “Get Started” was made a navbar CTA kind of late, and we decided not to move it to a new URL, and navbar highlighting is dependent on the directory in which a file resides.  If I remember aright, at the time it was felt that highlighting of “Learn & Discover” flagged that “Get Started” was part of that section of the site.  I don’t think changing the CTA button’s appearance is a good idea, but I’m also not married to the dashed line’s location.  There might be a way to have it link up to the CTA button, if desired; I’d have to dig back into the CSS to be sure.

**Comment by csaavedra** [comment]
I think one of the things that make the site confusing is this idea that "Get Started" has a toplevel button but it's also a subpage of "about" (which btw is actually called "Learn & Discover", another source of confusion -- see https://github.com/Igalia/wpewebkit.org/issues/173). With the rework of the contents of that page in https://github.com/Igalia/wpewebkit.org/pull/189 it would probably make sense to revisit the idea that this is a subsection of "about".
