### ISSUE TITLE
FAQ: inconsistent page heading

### ISSUE THREAD

**Issue by philn** [Igalia/wpewebkit.org#196]
The link to the FAQ is buried down https://wpewebkit.org/developers/

Clicking that link leads to https://wpewebkit.org/about/faq.html which has a "learn & discover" header. To be consistent, it should be "Developers"

Why is that page in Developers section anyway?

**Comment by csaavedra** [comment]
The explanation for this might be that the FAQ is also linked from the Learn and Discover section (WPE For Developers
 -> Frequently Asked Questions), so it's thought as being part of the Learn and Discover section, not Developers. I am not sure why it's in Developers too. I don't think it hurts necessarily, but yes it creates a bit of confusion that the header changes.

Should we remove it from Developers then? @aperezdc
