### ISSUE TITLE
Blog post on video post-production with HTML overlays

### ISSUE THREAD

**Issue by bkardell** [Igalia/wpewebkit.org#217]
[In our last post](https://wpewebkit.org/blog/2024-use-case-server-side-rendering.html) we provided 3 _very_ different use cases under the same banner 

> Some concrete use-cases can be:
> * Video post-production using HTML overlays.
> * Easy 3D rendering with WebGL that can be broadcasted as a video stream.
> * Reusing the same JavaScript code between a frontend web application and the backend processing.

I know @philn had some nice videos and I think some blog posts about this, but we have nothing on wpewebkit.org about it... It might be a nice/interesting one.

**Comment by philn** [comment]
The post from ~4 years ago, https://base-art.net/Articles/web-augmented-graphics-overlay-broadcasting-with-wpe-and-gstreamer/
