### ISSUE TITLE
“Code” page should not be under /about/

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#29]
Currently the [Code page](https://wpewebkit.org/about/code.html) is under `/about/code.html`, but this page is not _about_ WPE itself, so I think it would fit better to remove the `about/` fragment from the URL. My suggestion would be to change its path to plainly `/code`.

**Comment by aperezdc** [comment]
Also I think just `/code` is much nicer than `/code.html`—URLs identify *resources*, not the kind of file the resource is, having the `.html` suffix is completely unnecessary.

**Comment by bkardell** [comment]
I was thinking there might be the possibility that we do wind up having more under code..?

**Comment by aperezdc** [comment]
> I was thinking there might be the possibility that we do wind up having more under code..?

I'm not sure whether I am getting your point… If we end up with more content there, it shouldn't be a problem. We can add all the subpaths we may need in the future: `/code/repositories/`, `/code/contributing/`, etc. Right?

**Comment by bkardell** [comment]
Yeah, ok, seems fine I guess.
