### ISSUE TITLE
Playing a video from the demos carousel requires clicking twice

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#53]
I think it is expected clicking once in the thumbnail loads the YouTube embed _and_ starts playing the video at once; but the first click loads the embed, and a second click is needed afterwards to actually start playing the video. The carousel with videos in the front page was introduced by #36.

This happens at least in GNOME Web 3.38.x; probably because it tries to prevent video autoplay, unless the playback is initiated by the user.

I am not sure if there is any way around it, because of course before the embed is loaded there is technically no `<video>` from the point of view of the browser, so clicking on the image is not taken into account as “user initiated playback” because the first click replaces the thumbnail with the actual `<iframe>` and in turn once _that_ is loaded then the embed tries to autoplay—but as that's a new, previously unseen video for the browser, it prevents it from autoplaying.

**Comment by meyerweb** [comment]
This was resolved by PR 65 by @bkardell.
