### ISSUE TITLE
Multiple videos from the demos carousel can be played back simultaneously

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#54]
The videos carousel introduced in #36 allows playing more than once video simultaneously, even if only one is visible at a time.

Steps to reproduce:

1. Click on a video thumbnail. Start playing the video.
2. Click on the button at the righs side to switch to the next video.
3. Click the video thumbnail and start playing the newly visible video.

**Expected outcome**: Only the video and audio streams of the video being displayed are played.

**Actual outcome**: The audio for the first video is played along with the currently displayed video, which makes the video one is interested in watching difficult to understand.

**Comment by aperezdc** [comment]
FWIW, I don't know which degree of control we can have over a YouTube provided embed.

Maybe we can cobble something together by using `document.getElementsByTagName("video")` to obtain the video element _inside_ the `<iframe>` for the embed we want to control, and use the API (e.g. `.pause()` and so on) to at least prevent the hidden videos from adding background noise.

**Comment by meyerweb** [comment]
Apologies for the linked requests spam.  I apparently don’t fully understand how this works quite yet.

**Comment by aperezdc** [comment]
> Apologies for the linked requests spam. I apparently don’t fully understand how this works quite yet.

No problem at all, and at any rate thanks for working on this :+1:

**Comment by meyerweb** [comment]
This was resolved by PR 65 by @bkardell.
