### ISSUE TITLE
API docs are unreachable

### ISSUE THREAD

**Issue by philn** [Igalia/wpewebkit.org#56]
https://wpewebkit.org/reference/ doesn't seem to be reachable from any link. And the docs are outdated as well, referring to 2.23.90.

**Comment by aperezdc** [comment]
The documentation at that location was a test I did at some point to explore how to generate and publish the reference documentation. It needs some work to automate uploading the contents with each release.

**Comment by philn** [comment]
Any chance to have this fixed soon?

**Comment by aperezdc** [comment]
I have recently updated our release tooling to support [extracting documentation tarballs](https://git.sr.ht/~aperezdc/webkit-releng-toolbelt/commit/7e034230921e285b0ef1f22d1fd37db770395988). That's the first step to publish the reference documentation on the website, next thing is to pick their contents and include them under `/reference/<component>/<version>`.

Ideally, I would like to automate the process as much as possible: 11ty sure can generate a page with links to documentation per released version, and then have a Git hook on the server which automatically unpacks the documentation tarballs.

**Comment by csaavedra** [comment]
This has been fixed now with https://github.com/Igalia/wpewebkit.org/pull/232
