### ISSUE TITLE
Make social presence (chat room, Twitter, etc.) more visible

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#61]
These are currently “hidden” in the [Code section](https://wpewebkit.org/code/) which is not quite obvious. It would be good to have the information about how to contact people involved in the WPE project more prominently.

**Comment by meyerweb** [comment]
Adding them to the header and/or footer should be pretty easy, though the header would probably call harder for icons.  We could also add a “connection bar”, like a navbar but with ways to connect, say right below the header on every page, or right above the footer, or both.  Any particular preference?  Could also mock up some ideas if people want to see them visually.

**Comment by aperezdc** [comment]
I _think_ we might have been using an icon font at some point, or embedded SVGs—can't remember exactly, but it wouldn't be a problem to bring back the icons; or some icons.

It used to be some overly thick pre-footer (not sure how to call it, it can be seen [in this Web Archive snapshot](http://web.archive.org/web/20190213101459/https://wpewebkit.org/) for more context), which looked like this:

![Partial screenshot with a detail showing icons next to social media links in an older version of the WPE website from February 2019](https://user-images.githubusercontent.com/723451/110171627-ac436900-7e04-11eb-9c10-2eb90033f156.png)

**Comment by philn** [comment]
Would it be possible to have a standalone contact page too? That could be linked from the FAQ.

**Comment by meyerweb** [comment]
> Would it be possible to have a standalone contact page too? That could be linked from the FAQ.

I would say so, assuming we want to link to it from places like the Code page, which currently list contacts, so that other pages don’t have to list contacts out.  I still think there should be contact links in the footer of all pages.
