### ISSUE TITLE
Better organization and styling for releases

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#62]
The [releases page](https://wpewebkit.org/release/) looks like a list of posts, it would be nice to:

- Have the most recent source releases (both stable and development ones) highlighted somehow, maybe with some boxes at the top of the page.
- Make the list of older releases have smaller title texts—currently all releases look the same.
- List only the most recent _stable_ releases of each component in the front page (currently there are the “most N recent releases, no matter of which component”), then link to the releases page for the rest.

**Comment by meyerweb** [comment]
Oh, I am _so_ taking this one on.  I love this kind of stuff.

**Comment by meyerweb** [comment]
So the releases page **is** a list of posts, specifically those posts in `collections.release`.  Is the preferred intent to point directly at release tars from this page?  Or should it continue pointing at the release posts, and just not look like it’s a page of posts?

**Comment by aperezdc** [comment]
For reference, and for trying to give some ideas... we used to have the release tarballs linked in the front page:

- Previously: Four boxed columns, one per component, with the most recent stable and development releases, with direct links to the tarballs, quite at the top of the front page (can be seen [at the Web Archive](http://web.archive.org/web/20200613152515/https://wpewebkit.org/)).
- Even earlier: Two big buttons only linking to the tarballs (also [snapshotted here](http://web.archive.org/web/20190213101459/https://wpewebkit.org/)).

The issues with both these older versions were that they were taking at the very top of the front page, where it seems to be better to briefly explain what WPE is (in this regard we are doing much better now!), and that there were only links to the tarballs, without any obvious way of checking the release notes.

Probably we want to strike some middle ground between only two buttons and the four-box version (which looks a bit busy, IMHO), while still keeping project description at the top of the front page (like we currently do).

I hope this helps 😺️

**Comment by meyerweb** [comment]
I have a draft version in https://github.com/Igalia/wpewebkit.org/tree/issue-62 for review by others.  Please give it a look and let me know if you think this is a good direction, and if so, I can clean it up and create a pull request to merge into `master`.  If not, let me know what should be changed.  Thanks!

**Comment by bkardell** [comment]
I like the direction!  I think we need to work on the colors and contrast ratios but I expect that's what you'll do as we polish it up.  "Go for it" is my vote!
