### ISSUE TITLE
RSS feed not being updated

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#90]
As reported by `lanodan` on IRC:

> Just noticed but https://wpewebkit.org/feed.xml is horribly outdated for some reason (it's last update being in May 2020).

**Comment by meyerweb** [comment]
Bug confirmed.  I don’t see `feed.xml` in the repository, nor can I find anything that would generate such a thing.  Anyone have pointers so I can fix this one?

**Comment by meyerweb** [comment]
Update: I found it in the `old-2020` branch: https://github.com/Igalia/wpewebkit.org/blob/old-2020/feed.xml.  Does it just need to be migrated over to `master`?

**Comment by meyerweb** [comment]
Upon further investigation, I realized https://github.com/Igalia/wpewebkit.org/blob/old-2020/feed.xml is a Jekyll template.  Was the site migrated from Jekyll to 11ty in late 2020?  That would explain why the feed broke.

I found an official 11ty plugin for generating RSS/Atom files using a Nunjucks template: https://www.11ty.dev/docs/plugins/rss/.  I installed it locally and was able to generate an updated `feed.xml` by adapting the example code in the plugin’s documentation.

I don’t see a way to add 11ty plugins to the repository, though.  Even if I were to add the `feed.njk` file I’ve created, it would fail to work without the plugin.  How does one go about adding 11ty plugins to the site, or even verify whether it’s present?

**Comment by meyerweb** [comment]
FYI: I added a branch called `rss` with the [`feed.njk`](https://github.com/Igalia/wpewebkit.org/blob/rss/feed.njk) and [`.eleventy.js`](https://github.com/Igalia/wpewebkit.org/blob/rss/.eleventy.js) edits needed lines 13 and 19).  Once the site has https://www.11ty.dev/docs/plugins/rss/ installed, merging this should bring the feed back to life.

**Comment by bkardell** [comment]
> I don’t see a way to add 11ty plugins to the repository, though. Even if I were to add the feed.njk file I’ve created, it would fail to work without the plugin. How does one go about adding 11ty plugins to the site, or even verify whether it’s present?

It should be as simple as adding the changes from your package files that were created when you did npm install(s)

**Comment by aperezdc** [comment]
@meyerweb: Thanks for fixing this 🤗
