### ISSUE TITLE
Serve Source Sans font directly without using Google Fonts

### ISSUE THREAD

**Issue by aperezdc** [Igalia/wpewebkit.org#97]
Today I had a page load stall for a long time and it turns out it was a request to Google Fonts which never got answered:

![Screenshot of Epiphany with the Web Inspector open, showing the spinner next to the Google Fonts request](https://user-images.githubusercontent.com/723451/143305326-256409b0-8c8e-48ad-b0ae-c57efd38bbb4.png)

Once the request timed out the page was shown, but IMO we should remove usage of Google Fonts for two reasons:

- I would rather not have us contribute to Google tracking people around the web.
- The font is Open Source, we can serve the WOFF2/WOFF/TTF files from the same origin without depending on a third party.

**Comment by aperezdc** [comment]
This also affects local site preview (e.g. when using `npm run serve`) and that is terribly annoying.

**Comment by meyerweb** [comment]
I agree with both reasons to serve the font locally.  Are any of us particularly familiar with what’s needed to do here?  If not, I can do the digging and figure it out.

**Comment by aperezdc** [comment]
I can take a look later this week, as I've done the same a while ago for my personal website—filing the issue was mostly a reminder to not forget about it 😄
